[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=77.0.3"]

[project]
name="crispy-hummingbird"
description="Hummingbird UI template pack for django-crispy-forms"
readme = "README.md"
license = "MIT"
authors = [{name = "David Smith"}]
maintainers = [{name = "Ben Atkinson", email = "ben@streamlinedanalytics.co.uk"}]
requires-python = ">=3.10"
classifiers=[
  "Development Status :: 4 - Beta",
  "Environment :: Web Environment",
  "Framework :: Django",
  "Framework :: Django :: 5.2",
  "Framework :: Django :: 6.0",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
dynamic = [
  "version",
]
dependencies = [
  "django>=5.2",
  "django-crispy-forms>=2.3",
]
[dependency-groups]
test = [
  "pytest",
  "pytest-django",
]
lint = [
  "black",
  "isort",
  "flake8",
]
[project.urls]
"CI" = "https://github.com/Streamlined-Analytics/crispy-hummingbird/actions"
"Changelog" = "https://github.com/Streamlined-Analytics/crispy-hummingbird/releases"
"Homepage" = "https://github.com/Streamlined-Analytics/crispy-hummingbird"
"Issues" = "https://github.com/Streamlined-Analytics/crispy-hummingbird/issues"

[tool.setuptools.dynamic]
version = {attr = "crispy_hummingbird.__version__"}

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE= "tests.test_settings"
